### ISSUE TITLE
/api prefix is not added to endpoints in documentation therefore execute button wont work.

### ISSUE THREAD

**Issue by ta3pks** [celaltas/wheather_app#1]
Under /docs endpoint documentation assumes everything is under `/` however they should have been prefixed by `/api` this prevents documentation functions from running.

**Comment by celaltas** [comment]
The API endpoint is now accessible at /api. However, the "Execute" button in Swagger UI doesn't work because it uses curl, which by default doesn't accept self-signed certificates.

**Comment by ta3pks** [comment]
thanks for the rapid reponse and sorry for the delay on our end
